CREATE DATABASE ECOMMERCE
USE ECOMMERCE

CREATE TABLE USUARIOS (IDUSUARIO VARCHAR (5) PRIMARY KEY, NOMBRE CHAR (20), CORREO VARCHAR (25), CONTRASEÑA VARCHAR (10)) 
CREATE TABLE PRODUCTOS (IDPRODUCTO VARCHAR (5) PRIMARY KEY, NOMBRE CHAR (20), PRECIO NUMERIC (10), FOTO VARCHAR (50))  
CREATE TABLE DOMICILIO (IDDOMICILIO VARCHAR (10) PRIMARY KEY, CALLE VARCHAR (20), NUMERO NUMERIC (10), COLONIA VARCHAR (15), CIUDAD CHAR (20), CP NUMERIC (10))  
CREATE TABLE INVENTARIO (IDINVENTARIO VARCHAR (5) PRIMARY KEY, STOCK NUMERIC (10), PREVEEDOR VARCHAR (15))
CREATE TABLE ENVIOS (IDENVIOS VARCHAR (5) PRIMARY KEY, IDUSUARIO VARCHAR (5), IDDOMICILIO VARCHAR (10), IDPRODUCTO VARCHAR (5))
CREATE TABLE COMPRAS (IDCOMPRAS VARCHAR (5) PRIMARY KEY, IDUSUARIO VARCHAR (5), FECHA_COMPRA VARCHAR (10), TOTAL NUMERIC (10))
CREATE TABLE CARRITO (IDCARRITO VARCHAR (10) PRIMARY KEY, IDUSUARIO VARCHAR (5), IDPRODUCTO VARCHAR (5),CANTIDAD NUMERIC (10), PRECIO NUMERIC (10))
CREATE TABLE PAGOS (IDPAGOS VARCHAR (5) PRIMARY KEY, IDCOMPRAS VARCHAR (5), MONTO NUMERIC (10), FECHA_PAGO VARCHAR (20), METODO_PAGO VARCHAR (20))
CREATE TABLE CATEGORIAS (IDCATEGORIA VARCHAR (10) PRIMARY KEY, NOMBRE CHAR (15), DESCRIPCION VARCHAR (20))
CREATE TABLE COMENTARIOS (IDCOMETARIO VARCHAR (30) PRIMARY KEY, IDUSUARIO VARCHAR (5), COMETARIO CHAR (50)) 
CREATE TABLE PRODUCTOS_COMPA(IDPC VARCHAR (5) PRIMARY KEY, IDPRODUCTO VARCHAR (5),CANTIDAD NUMERIC (10), PRECIO NUMERIC (10), IDCOMPRA VARCHAR (5))




INSERT INTO USUARIOS(IDUSUARIO,NOMBRE,CORREO,CONTRASEÑA) VALUES ('IS01', 'JAVIER', 'JAVIER@USUARIO.COM', '12345678') 
INSERT INTO USUARIOS(IDUSUARIO,NOMBRE,CORREO,CONTRASEÑA) VALUES ('IS02', 'RAUL', 'RAULR@USUARIO.COM', '12345678') 
INSERT INTO USUARIOS(IDUSUARIO,NOMBRE,CORREO,CONTRASEÑA) VALUES ('IS03', 'SEBASTIAN', 'SEBASTIAN@USUARIO.COM', '12345678') 
INSERT INTO USUARIOS(IDUSUARIO,NOMBRE,CORREO,CONTRASEÑA) VALUES ('IS04', 'PAMELA', 'PAMELA@USUARIO.COM', '12345678') 

INSERT INTO PRODUCTOS(IDPRODUCTO,NOMBRE,PRECIO,FOTO) VALUES ('IP01', 'PHONES', 12.000 , 'IMG/FOTO.WEBO')
INSERT INTO PRODUCTOS(IDPRODUCTO,NOMBRE,PRECIO,FOTO) VALUES ('IP02', 'SPEAKER', 2000 , 'IMG/FOTO.WEBP')
INSERT INTO PRODUCTOS(IDPRODUCTO,NOMBRE,PRECIO,FOTO) VALUES ('IP03', 'SMART MATCH', 5000 , 'IMG/FOTO.WEBP')
INSERT INTO PRODUCTOS(IDPRODUCTO,NOMBRE,PRECIO,FOTO) VALUES ('IP04', 'GAMES', 1000 , 'IMG/FOTO.WEBP')


INSERT INTO DOMICILIO(IDDOMICILIO,CALLE,NUMERO,COLONIA,CIUDAD,CP) VALUES ('ID01', 'CALLE_1', 2500, 'VILLAHERMOSA', 'CHIHUAHUA', 31770)
INSERT INTO DOMICILIO(IDDOMICILIO,CALLE,NUMERO,COLONIA,CIUDAD,CP) VALUES ('ID02', 'CALLE_2', 2600, 'ENCINOS', 'CHIHUAHUA', 31770)
INSERT INTO DOMICILIO(IDDOMICILIO,CALLE,NUMERO,COLONIA,CIUDAD,CP) VALUES ('ID03', 'CALLE_3', 2700, 'CENTRO', 'CHIHUAHUA', 31770)
INSERT INTO DOMICILIO(IDDOMICILIO,CALLE,NUMERO,COLONIA,CIUDAD,CP) VALUES ('ID04', 'CALLE_4', 2800, 'DUBLAN', 'CHIHUAHUA', 31770)

INSERT INTO INVENTARIO(IDINVENTARIO,STOCK,PREVEEDOR) VALUES ('IV01', 1000, 'SAMSUNG')
INSERT INTO INVENTARIO(IDINVENTARIO,STOCK,PREVEEDOR) VALUES ('IV02', 265, 'JBL')
INSERT INTO INVENTARIO(IDINVENTARIO,STOCK,PREVEEDOR) VALUES ('IV03', 801, 'IPHONE')
INSERT INTO INVENTARIO(IDINVENTARIO,STOCK,PREVEEDOR) VALUES ('IV04', 23, 'HUAWEI')

INSERT INTO ENVIOS(IDENVIOS,IDUSUARIO,IDDOMICILIO,IDPRODUCTO) VALUES ('EN01', 'IS01','ID01','IP01')
INSERT INTO ENVIOS(IDENVIOS,IDUSUARIO,IDDOMICILIO,IDPRODUCTO) VALUES ('EN02', 'IS02','ID02','IP02')
INSERT INTO ENVIOS(IDENVIOS,IDUSUARIO,IDDOMICILIO,IDPRODUCTO) VALUES ('EN03', 'IS03','ID03','IP03')
INSERT INTO ENVIOS(IDENVIOS,IDUSUARIO,IDDOMICILIO,IDPRODUCTO) VALUES ('EN04', 'IS04','ID04','IP04')

INSERT INTO COMPRAS(IDCOMPRAS,IDUSUARIO,FECHA_COMPRA,TOTAL) VALUES ('IC01', 'IP01',  '01/01/24', 2500)
INSERT INTO COMPRAS(IDCOMPRAS,IDUSUARIO,FECHA_COMPRA,TOTAL) VALUES ('IC02', 'IP02',  '12/04/24', 500)
INSERT INTO COMPRAS(IDCOMPRAS,IDUSUARIO,FECHA_COMPRA,TOTAL) VALUES ('IC03', 'IP03',  '09/08/24', 3500)
INSERT INTO COMPRAS(IDCOMPRAS,IDUSUARIO,FECHA_COMPRA,TOTAL) VALUES ('IC04', 'IP04',  '22/12/24', 1500)

INSERT INTO CARRITO(IDCARRITO,IDUSUARIO,IDPRODUCTO,CANTIDAD,PRECIO) VALUES ('ICAR01', 'IS01', 'IP01', 3, 2560)
INSERT INTO CARRITO(IDCARRITO,IDUSUARIO,IDPRODUCTO,CANTIDAD,PRECIO) VALUES ('ICAR02', 'IS02', 'IP02', 6, 3560)
INSERT INTO CARRITO(IDCARRITO,IDUSUARIO,IDPRODUCTO,CANTIDAD,PRECIO) VALUES ('ICAR03', 'IS03', 'IP03', 9, 5560)
INSERT INTO CARRITO(IDCARRITO,IDUSUARIO,IDPRODUCTO,CANTIDAD,PRECIO) VALUES ('ICAR04', 'IS04', 'IP04', 2, 560)

INSERT INTO PAGOS(IDPAGOS,IDCOMPRAS,MONTO,FECHA_PAGO,METODO_PAGO) VALUES ('IPG01', 'IC01', 2500, '17/05/24', 'TRANSFERENCIA')
INSERT INTO PAGOS(IDPAGOS,IDCOMPRAS,MONTO,FECHA_PAGO,METODO_PAGO) VALUES ('IPG02', 'IC02', 500, '17/05/24', 'TRANSFERENCIA')
INSERT INTO PAGOS(IDPAGOS,IDCOMPRAS,MONTO,FECHA_PAGO,METODO_PAGO) VALUES ('IPG03', 'IC03', 2800, '17/05/24', 'TRANSFERENCIA')
INSERT INTO PAGOS(IDPAGOS,IDCOMPRAS,MONTO,FECHA_PAGO,METODO_PAGO) VALUES ('IPG04', 'IC04', 5500, '17/05/24', 'TRANSFERENCIA')

INSERT INTO CATEGORIAS(IDCATEGORIA,NOMBRE,DESCRIPCION) VALUES ('ICT01', 'PHONES', 'IPHONE 15 PRO')
INSERT INTO CATEGORIAS(IDCATEGORIA,NOMBRE,DESCRIPCION) VALUES ('ICT02', 'SPEAKERS', 'JBL SERIES 12')
INSERT INTO CATEGORIAS(IDCATEGORIA,NOMBRE,DESCRIPCION) VALUES ('ICT03', 'SMART WATCH', 'SERIES 12 TITANUIM')
INSERT INTO CATEGORIAS(IDCATEGORIA,NOMBRE,DESCRIPCION) VALUES ('ICT04', 'GAMES', 'WARZONE')

INSERT INTO COMENTARIOS(IDCOMETARIO,IDUSUARIO,COMETARIO) VALUES ('ICM01', 'IS01', 'MUY BUEN PRODUCTO GRACIAS')
INSERT INTO COMENTARIOS(IDCOMETARIO,IDUSUARIO,COMETARIO) VALUES ('ICM02', 'IS02', 'EXCELENTE PRODUCTO GRACIAS')
INSERT INTO COMENTARIOS(IDCOMETARIO,IDUSUARIO,COMETARIO) VALUES ('ICM03', 'IS03', 'LLEGO CON FALLAS')
INSERT INTO COMENTARIOS(IDCOMETARIO,IDUSUARIO,COMETARIO) VALUES ('ICM04', 'IS04', 'GRACIAS MUCHA CALIDAD DE LOS MATERIALES')

INSERT INTO PRODUCTOS_COMPA(IDPC,IDPRODUCTO,CANTIDAD,PRECIO,IDCOMPRA) VALUES ('IDP01', 'IP01', 1, 2500, 'IC01')
INSERT INTO PRODUCTOS_COMPA(IDPC,IDPRODUCTO,CANTIDAD,PRECIO,IDCOMPRA) VALUES ('IDP02', 'IP02', 2, 5500, 'IC02')
INSERT INTO PRODUCTOS_COMPA(IDPC,IDPRODUCTO,CANTIDAD,PRECIO,IDCOMPRA) VALUES ('IDP03', 'IP03', 3, 8500, 'IC03')
INSERT INTO PRODUCTOS_COMPA(IDPC,IDPRODUCTO,CANTIDAD,PRECIO,IDCOMPRA) VALUES ('IDP04', 'IP04', 4, 22500, 'IC04')



--INNER JOIN

--mostrar los envíos realizados, incluyendo el nombre del usuario y la dirección de entrega.
SELECT E.IDENVIOS, U.NOMBRE AS USUARIO, D.CALLE, D.CIUDAD, D.CP FROM ENVIOS E INNER JOIN USUARIOS U ON E.IDUSUARIO = U.IDUSUARIO INNER JOIN DOMICILIO D ON E.IDDOMICILIO = D.IDDOMICILIO
--mostrar los productos que los usuarios han añadido a su carrito, junto con la cantidad y el precio que sea mayor de 2000
SELECT C.IDUSUARIO, C.IDPRODUCTO, P.NOMBRE AS PRODUCTO, C.CANTIDAD, C.PRECIO FROM CARRITO C INNER JOIN PRODUCTOS P ON C.IDPRODUCTO = P.IDPRODUCTO WHERE C.PRECIO > 2000
--mostrar los productos comprados en cada compra, junto con la cantidad y el precio de cada producto que sea menor de 6000
SELECT PC.IDCOMPRA, P.NOMBRE AS PRODUCTO, PC.CANTIDAD, PC.PRECIO FROM PRODUCTOS_COMPA PC INNER JOIN PRODUCTOS P ON PC.IDPRODUCTO = P.IDPRODUCTO WHERE PC.PRECIO < 6000

--PRODUCTO CARTESIONO 

--mostrar los detalles de envíos junto con la dirección de entrega asociada.
SELECT E.IDENVIOS, E.IDUSUARIO, D.CALLE, D.CIUDAD, D.CP FROM ENVIOS E, DOMICILIO D WHERE E.IDDOMICILIO = D.IDDOMICILIO
--mostar los productos que los usuarios tienen en su carrito, con el nombre y el precio de cada producto.
SELECT C.IDCARRITO, C.IDUSUARIO, P.IDPRODUCTO, P.NOMBRE, P.PRECIO FROM CARRITO C, PRODUCTOS P WHERE C.IDPRODUCTO = P.IDPRODUCTO
--mostrar el metodo de pago y el monto ademas del id del pago y de la compra
SELECT P.IDPAGOS,  P.METODO_PAGO, C.IDCOMPRAS, C.TOTAL FROM PAGOS P, COMPRAS C WHERE P.IDCOMPRAS = C.IDCOMPRAS


--FUNCIONES DE COLUMNAS Y CONSULTAS DE RESUMEN 

--mostrar el promedio del monto total de las compras para cada método de pago.
SELECT P.METODO_PAGO, AVG(c.TOTAL) AS PROMEDIO_TOTAL FROM PAGOS P INNER JOIN COMPRAS C ON P.IDCOMPRAS = C.IDCOMPRAS GROUP BY P.METODO_PAGO
--Mostrar la cantidad mínima de productos en stock por proveedor
SELECT I.PREVEEDOR, MIN(I.STOCK) AS STOCK FROM INVENTARIO I GROUP BY I.PREVEEDOR
--mostrar el total de ingresos por cada producto vendido
SELECT P.NOMBRE AS PRODUCTO, SUM(PRODUCTOS_COMPA.PRECIO * PRODUCTOS_COMPA.CANTIDAD) AS INGRESOS_TOTALES FROM PRODUCTOS P INNER JOIN PRODUCTOS_COMPA ON P.IDPRODUCTO = PRODUCTOS_COMPA.IDPRODUCTO GROUP BY P.NOMBRE


