create database ecommerceNueva;

use ecommerceNueva;

-- CREAMOS LAS TABLAS 

CREATE TABLE USUARIOS (
    IDUSUARIO integer not null auto_increment,
    NOMBRE VARCHAR(20),
    CORREO VARCHAR(25),
    CONTRASENA VARCHAR(10),
    primary key (IDUSUARIO)
);

CREATE TABLE PRODUCTOS (
    IDPRODUCTO integer not null auto_increment,
    NOMBRE CHAR(50),
    PRECIO NUMERIC(10, 2), -- Agregado precisión y escala para el precio
    FOTO VARCHAR(50),
    primary key (IDPRODUCTO)
);

CREATE TABLE PRODUCTOS2 (
    IDPRODUCTO integer not null auto_increment,
    NOMBRE CHAR(50),
    PRECIO NUMERIC(10, 2), -- Agregado precisión y escala para el precio
    FOTO VARCHAR(50),
    CATEGORIA VARCHAR (20),
    primary key (IDPRODUCTO)
);

CREATE TABLE DOMICILIO (
    IDDOMICILIO integer not null auto_increment,
    CALLE VARCHAR(20),
    NUMERO NUMERIC(10),
    COLONIA VARCHAR(15),
    CIUDAD CHAR(20),
    CP NUMERIC(10),
    PRIMARY KEY (IDDOMICILIO)
);

CREATE TABLE INVENTARIO (
    IDINVENTARIO integer not null auto_increment,
    STOCK NUMERIC(10),
    PREVEEDOR VARCHAR(15),
    PRIMARY KEY (IDINVENTARIO)
);

CREATE TABLE ENVIOS (
    IDENVIOS integer not null auto_increment,
    IDUSUARIO VARCHAR(5),
    IDDOMICILIO VARCHAR(10),
    IDPRODUCTO VARCHAR(5),
    PRIMARY KEY (IDENVIOS)
);

CREATE TABLE COMPRAS (
    IDCOMPRAS integer not null auto_increment,
    IDUSUARIO VARCHAR(5),
    FECHA_COMPRA VARCHAR(10),
    TOTAL NUMERIC(10),
    PRIMARY KEY (IDCOMPRAS)
);

CREATE TABLE CARRITO (
    IDCARRITO integer not null auto_increment,
    IDUSUARIO VARCHAR(5),
    IDPRODUCTO VARCHAR(5),
    CANTIDAD NUMERIC(10),
    PRECIO NUMERIC(10),
    PRIMARY KEY (IDCARRITO)
);

CREATE TABLE PAGOS (
    IDPAGOS integer not null auto_increment,
    IDCOMPRAS VARCHAR(5),
    MONTO NUMERIC(10),
    FECHA_PAGO VARCHAR(20),
    METODO_PAGO VARCHAR(20),
    PRIMARY KEY (IDPAGOS)
);

CREATE TABLE CATEGORIAS (
    IDCATEGORIA integer not null auto_increment,
    NOMBRE CHAR(15),
    DESCRIPCION VARCHAR(20),
    PRIMARY KEY (IDCATEGORIA)
);

CREATE TABLE COMENTARIOS (
    IDCOMENTARIO integer not null auto_increment,
    IDUSUARIO VARCHAR(5),
    COMENTARIO CHAR(50),
    PRIMARY KEY (IDCOMENTARIO)
);

CREATE TABLE PRODUCTOS_COMPA (
    IDPC integer not null auto_increment,
    IDPRODUCTO VARCHAR(5),
    CANTIDAD NUMERIC(10),
    PRECIO NUMERIC(10),
    IDCOMPRA VARCHAR(5),
    PRIMARY KEY (IDPC)
);

select *from USUARIOS
select *from PRODUCTOS
select *from COMENTARIOS
select *from DOMICILIO
select *from INVENTARIO
select *from ENVIOS
select *from COMPRAS
select *from CARRITO
select *from PAGOS
select *from CATEGORIAS
select *from PRODUCTOS_COMPA


-- AGREGAR VALORES A LA TABLA  

-- Insertar datos en la tabla USUARIOS

INSERT INTO USUARIOS (IDUSUARIO, NOMBRE, CORREO, CONTRASENA) 
VALUES (0, 'JAVIER', 'JAVIER@USUARIO.COM', '12345678');

INSERT INTO USUARIOS (IDUSUARIO, NOMBRE, CORREO, CONTRASENA) 
VALUES (0, 'LUIS', 'LUIS@USUARIO.COM', '09876789');

INSERT INTO USUARIOS (IDUSUARIO, NOMBRE, CORREO, CONTRASENA) 
VALUES (0, 'JAVI', 'JAVI@USUARIO.COM', '19283746');

INSERT INTO USUARIOS (IDUSUARIO, NOMBRE, CORREO, CONTRASENA) 
VALUES (0, 'RAUL', 'RAUL@USUARIO.COM', '98765');

INSERT INTO USUARIOS (IDUSUARIO, NOMBRE, CORREO, CONTRASENA) 
VALUES (0, 'SEBAS', 'SEBAS@USUARIO.COM', '12345');


-- Insertar datos en la tabla PRODUCTOS

INSERT INTO PRODUCTOS (IDPRODUCTO, NOMBRE, PRECIO, FOTO) 
VALUES (0, 'PHONES 16 PRO MAX', 12.00, 'IMG/FOTO.WEB');

INSERT INTO PRODUCTOS (IDPRODUCTO, NOMBRE, PRECIO, FOTO) 
VALUES (0, 'SPEAKERS JBL', 122.00, 'IMG/FOTO.WEB');

INSERT INTO PRODUCTOS (IDPRODUCTO, NOMBRE, PRECIO, FOTO) 
VALUES (0, 'GAMES CALL OF DUTY', 2.00, 'IMG/FOTO.WEB');

INSERT INTO PRODUCTOS (IDPRODUCTO, NOMBRE, PRECIO, FOTO) 
VALUES (0, 'BALON SOCCER #5', 8.00, 'IMG/FOTO.WEB');

INSERT INTO PRODUCTOS (IDPRODUCTO, NOMBRE, PRECIO, FOTO) 
VALUES (0, 'BALON FUT 7 #4', 8.00, 'IMG/FOTO.WEB');




INSERT INTO PRODUCTOS2 (IDPRODUCTO, NOMBRE, PRECIO, FOTO, CATEGORIA) 
VALUES (0, 'PELOTA PLAYA', 2.00, 'DEFAUL.WEB', 'LAPTOP');




-- Insertar datos en la tabla DOMICILIO
INSERT INTO DOMICILIO(IDDOMICILIO, CALLE, NUMERO, COLONIA, CIUDAD, CP) 
VALUES (0, 'CALLE_1', 2500, 'VILLAHERMOSA', 'CHIHUAHUA', 31770);

INSERT INTO DOMICILIO(IDDOMICILIO, CALLE, NUMERO, COLONIA, CIUDAD, CP) 
VALUES (0, 'CALLE_2', 2600, 'ENCINOS', 'CHIHUAHUA', 31770);

INSERT INTO DOMICILIO(IDDOMICILIO, CALLE, NUMERO, COLONIA, CIUDAD, CP) 
VALUES (0, 'CALLE_3', 2700, 'CENTRO', 'CHIHUAHUA', 31770);

INSERT INTO DOMICILIO(IDDOMICILIO, CALLE, NUMERO, COLONIA, CIUDAD, CP) 
VALUES (0, 'CALLE_4', 2800, 'DUBLAN', 'CHIHUAHUA', 31770);


-- Insertar datos en la tabla INVENTARIO
INSERT INTO INVENTARIO(IDINVENTARIO, STOCK, PREVEEDOR) 
VALUES (0, 1000, 'SAMSUNG');

INSERT INTO INVENTARIO(IDINVENTARIO, STOCK, PREVEEDOR) 
VALUES (0, 265, 'JBL');

INSERT INTO INVENTARIO(IDINVENTARIO, STOCK, PREVEEDOR) 
VALUES (0, 801, 'IPHONE');

INSERT INTO INVENTARIO(IDINVENTARIO, STOCK, PREVEEDOR) 
VALUES (0, 23, 'HUAWEI');


-- Insertar datos en la tabla ENVIOS
INSERT INTO ENVIOS(IDENVIOS, IDUSUARIO, IDDOMICILIO, IDPRODUCTO) 
VALUES (0, 'IS01', 'ID01', 'IP01');

INSERT INTO ENVIOS(IDENVIOS, IDUSUARIO, IDDOMICILIO, IDPRODUCTO) 
VALUES (0, 'IS02', 'ID02', 'IP02');

INSERT INTO ENVIOS(IDENVIOS, IDUSUARIO, IDDOMICILIO, IDPRODUCTO) 
VALUES (0, 'IS03', 'ID03', 'IP03');

INSERT INTO ENVIOS(IDENVIOS, IDUSUARIO, IDDOMICILIO, IDPRODUCTO) 
VALUES (0, 'IS04', 'ID04', 'IP04');


-- Insertar datos en la tabla COMPRAS
INSERT INTO COMPRAS(IDCOMPRAS, IDUSUARIO, FECHA_COMPRA, TOTAL) 
VALUES (0, 'IP01', '01/01/24', 2500);

INSERT INTO COMPRAS(IDCOMPRAS, IDUSUARIO, FECHA_COMPRA, TOTAL) 
VALUES (0, 'IP02', '12/04/24', 500);

INSERT INTO COMPRAS(IDCOMPRAS, IDUSUARIO, FECHA_COMPRA, TOTAL) 
VALUES (0, 'IP03', '09/08/24', 3500);

INSERT INTO COMPRAS(IDCOMPRAS, IDUSUARIO, FECHA_COMPRA, TOTAL) 
VALUES (0, 'IP04', '22/12/24', 1500);


-- Insertar datos en la tabla CARRITO
INSERT INTO CARRITO(IDCARRITO, IDUSUARIO, IDPRODUCTO, CANTIDAD, PRECIO) 
VALUES (0, 'IS01', 'IP01', 3, 2560);

INSERT INTO CARRITO(IDCARRITO, IDUSUARIO, IDPRODUCTO, CANTIDAD, PRECIO) 
VALUES (0, 'IS02', 'IP02', 6, 3560);

INSERT INTO CARRITO(IDCARRITO, IDUSUARIO, IDPRODUCTO, CANTIDAD, PRECIO) 
VALUES (0, 'IS03', 'IP03', 9, 5560);

INSERT INTO CARRITO(IDCARRITO, IDUSUARIO, IDPRODUCTO, CANTIDAD, PRECIO) 
VALUES (0, 'IS04', 'IP04', 2, 560);


-- Insertar datos en la tabla PAGOS
INSERT INTO PAGOS(IDPAGOS, IDCOMPRAS, MONTO, FECHA_PAGO, METODO_PAGO) 
VALUES (0, 'IC01', 2500, '17/05/24', 'TRANSFERENCIA');

INSERT INTO PAGOS(IDPAGOS, IDCOMPRAS, MONTO, FECHA_PAGO, METODO_PAGO) 
VALUES (0, 'IC02', 500, '17/05/24', 'TRANSFERENCIA');

INSERT INTO PAGOS(IDPAGOS, IDCOMPRAS, MONTO, FECHA_PAGO, METODO_PAGO) 
VALUES (0, 'IC03', 2800, '17/05/24', 'TRANSFERENCIA');

INSERT INTO PAGOS(IDPAGOS, IDCOMPRAS, MONTO, FECHA_PAGO, METODO_PAGO) 
VALUES (0, 'IC04', 5500, '17/05/24', 'TRANSFERENCIA');


-- Insertar datos en la tabla CATEGORIAS
INSERT INTO CATEGORIAS(IDCATEGORIA, NOMBRE, DESCRIPCION) 
VALUES (0, 'PHONES', 'IPHONE 15 PRO');

INSERT INTO CATEGORIAS(IDCATEGORIA, NOMBRE, DESCRIPCION) 
VALUES (0, 'SPEAKERS', 'JBL SERIES 12');

INSERT INTO CATEGORIAS(IDCATEGORIA, NOMBRE, DESCRIPCION) 
VALUES (0, 'SMART WATCH', 'SERIES 12 TITANIUM');

INSERT INTO CATEGORIAS(IDCATEGORIA, NOMBRE, DESCRIPCION) 
VALUES ('ICT04', 'GAMES', 'WARZONE');


-- Insertar datos en la tabla COMENTARIOS
INSERT INTO COMENTARIOS(IDCOMENTARIO, IDUSUARIO, COMENTARIO) 
VALUES (0, 'IS01', 'MUY BUEN PRODUCTO, GRACIAS');

INSERT INTO COMENTARIOS(IDCOMENTARIO, IDUSUARIO, COMENTARIO) 
VALUES (0, 'IS02', 'EXCELENTE PRODUCTO, GRACIAS');

INSERT INTO COMENTARIOS(IDCOMENTARIO, IDUSUARIO, COMENTARIO) 
VALUES (0, 'IS03', 'LLEGO CON FALLAS');

INSERT INTO COMENTARIOS(IDCOMENTARIO, IDUSUARIO, COMENTARIO) 
VALUES (0, 'IS04', 'GRACIAS, MUCHA CALIDAD DE LOS MATERIALES');


-- Insertar datos en la tabla PRODUCTOS_COMPA
INSERT INTO PRODUCTOS_COMPA(IDPC, IDPRODUCTO, CANTIDAD, PRECIO, IDCOMPRA) 
VALUES (0, 'IP01', 1, 2500, 'IC01');

INSERT INTO PRODUCTOS_COMPA(IDPC, IDPRODUCTO, CANTIDAD, PRECIO, IDCOMPRA) 
VALUES (0, 'IP02', 2, 5500, 'IC02');

INSERT INTO PRODUCTOS_COMPA(IDPC, IDPRODUCTO, CANTIDAD, PRECIO, IDCOMPRA) 
VALUES (0, 'IP03', 3, 8500, 'IC03');

INSERT INTO PRODUCTOS_COMPA(IDPC, IDPRODUCTO, CANTIDAD, PRECIO, IDCOMPRA) 
VALUES (0, 'IP04', 4, 22500, 'IC04');
